;CONFIGURING PLUGIN BEHAVIOR
[Options]

;Specifies when the settings are read from this section:
;  0: only when the plugin is loaded into memory
;  1: for each access to the plugin
ReadOptionsEveryTime=0

;Enables control with Scroll Lock key:
;  0: plugin is always on
;  1: enable plugin by Scroll Lock key
ScrollLockControl=0

;Controls plugin executing depending on the type of window:
;  1: execute only in modal windows ("Find Files", "Synchronize directories", Overwrite dialog)
;  0: execute conditions defined by keys FindFiles, SyncDirs, TCWindow, QuickView, Lister4, OverWrite
ModalOnly=0

;If ModalOnly=0, controls plugin executing (1: allow; 0: disallow):
;  in window "Find Files"
FindFiles=1
;  in window "Synchronize directories"
SyncDirs=1
;  in main window of Total Commander
TCWindow=1
;  with quick view
QuickView=0
;  in Lister when activated view mode with plugins (key 4) or when switching between files (keys N and P)
Lister4=0
;  when starts Lister without Total Commander main window (from command line with parameter /S=L)
ListerDirectly=0
;  in Overwrite dialog
OverWrite=1

;Controls plugin executing depending on the file extension:
;  1: execute only for files with extensions, defined in section Editor of file AppLoader.ini or in section Extensions of Total Commander configuration file (see key UseTCExtensions)
;  0: execute for files with any extension
IfIsExtOnly=0

;Specifies the action on the Lister window (including quick view) after plugin executing:
;  0: leave open
;  1: when file was extracted/downloaded from archive/FTP-server/WFX-plugin: normal Lister window – hide, quick view window – leave open; in other cases – close
;  2: close anyway
ListerState=1

;If ListerState=0:
;Specifies the behavior for the case where Lister is left open after plugin executing:
;  1: switch Lister to the next appropriate plugin
;  0: leave AppLoader in Lister
NextPlugin=1

;Defines how to pass command line parameters to the applications:
;  0: Parameters by application. Files divides into groups depending on association with applications. Starts separate application instance for each group. Command line parameters gets from section Editor (key - full name of application)
;  1: Parameters by extension. Start type defined by key ParamsByExtMode
ParamsMode=1

;If ParamsMode=1:
;Defines how to pass command line parameters to the applications:
;  0: Files divides into groups depending on association with applications. Starts separate application instance for each group. Command line parameters gets from section Editor (key that contains extension of first file in group)
;  1: Files divides into groups depending on extension. Starts separate application instance for each group. Command line parameters gets from section Editor (key that contains extension of group files)
;  2: Starts separate application instance for each file. Command line parameters gets from section Editor (key that contains file extension)
ParamsByExtMode=0

;Defines source of application associations by extensions:
;  1: section Extensions in Total Commander configurstion file
;  0: section Editor in file AppLoader.ini
UseTCExtensions=0

;When plugin execute in dialog "Find Files" this option allows to copy search text into the clipboard, if checked search option "Find text":
;  1: enable function
;  0: disable function
CopySearchTextToClip=1

;If IfIsExtOnly=0:
;  Default application. Name of the application which will starts for file types (extensions) that do not have their own application
DefaultEditor=notepad

;NAMES AND COMMAND LINE PARAMETERS OF APPLICATIONS
;Read the help file for more information on this section.
[Editor]
lng,ini=notepad
bmp=mspaint
:dir=explorer
rpf="C:\OneDrive\Apps\RAPT_6.6.8\RAPTW.exe"

;HOT KEYS
;See list of key codes in file ReadMe\KeyCodes.html. If code is not defined hot key will not assign. Can be used both decimal and hexadecimal code values. For example, F12 – 123 or 0x7B.
;Available modifier values: A – Alt, C – Control, S – Shift. Sample: CAS – Control+Alt+Shift.
[HotKeys]

;Code of hot key (for example, 123 – F12), which can be used in Lister to open the file with associated application
AppFromLister_key=123

;Modifier for hotkey specified in the key AppFromLister_key
AppFromLister_mod=C

;Code of hot key (for example, 0x78 – F9), which can be used in Lister to open the file with associated in OS application
DefSysAppFromLister_key=120

;Modifier for hotkey specified in the key DefSysAppFromLister_key
DefSysAppFromLister_mod=C

;POSITIONS OF Total Commander INTERFACE ELEMENTS
;If CopySearchTextToClip=1 these keys used to search for interface elements by their location. Plugin will search for an element at position plus/minus 5 pixels from the specified value.
[TCPos]

;Position of top left corner of option "Find text" in dialog "Find Files" (for Total Commander 8.01x32, 8.50b5x32: 5; 116, 8.50b5x64: 5; 114)
IsSearchTextLeft=5
IsSearchTextTop=116

;Position of top left corner of field "Find text" in dialog "Find Files" (for Total Commander 8.01x32, 8.50b5x32, 8.50b5x64: 85; 114)
SearchTextLeft=85
SearchTextTop=114