[Options]
;Path=
Path64=%COMMANDER_PATH%\Plugins\wlx\TCSumatraPDF\SumatraPDF.exe
;DirIniL=%COMMANDER_PATH%\Plugins\wlx\TCSumatraPDF\SumatraPDF\DirIniL\
;DirIniQ=%COMMANDER_PATH%\Plugins\wlx\TCSumatraPDF\SumatraPDF\DirIniQ\